name: Deploy Backend to Azure

on:
  push:
    branches:
      - cloud-deployment-testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build backend with Maven
      run: mvn -f ./backend/pom.xml clean package

    - name: Build Docker image
      run: docker build -t studbuds-backend ./backend

    - name: Deploy to Azure Web App (Docker-based)
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: studbuds-backend
